name: Deploy Swagger UI to GitHub Pages

on:
  push:
    branches:
      - main # main 브랜치에 push 시 실행
  pull_request:
    branches:
      - main # main 브랜치로 PR 시 실행

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Swagger UI Dist
        run: |
          npm install swagger-ui-dist
          mkdir -p public
          cp -r ./node_modules/swagger-ui-dist/* public/

      - name: Fetch OpenAPI spec
        run: |
          curl -o public/openapi.json https://pickable-v2.github.io/v3/api-docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
